services:
  - type: web
    name: inazuma-battle-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: 74f5dbfcbe691f445d3a2cd69f4d7213c7f48688bde54d2586b38f741fd7db63
        generateValue: true
      - key: FRONTEND_URL
        sync: false
